apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pereira6/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: services-config
              key: JWT_SECRET
        - name: DB_HOST
          value: "postgres-user"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "user_service_db"
        - name: DB_USER
          value: "Daniel"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: services-config
              key: USER_SERVICE_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30002 