apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pereira6/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: "postgres-user"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "user_service_db"
        - name: DB_USER
          value: "grupo6_admin"
        - name: DB_PASSWORD
          value: "grupo6"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002 