apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:3002']
      - job_name: 'shopping-service'
        static_configs:
          - targets: ['shopping-service:3003']
      - job_name: 'home-task-service'
        static_configs:
          - targets: ['home-task-service:3001'] 