apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-task-service
  template:
    metadata:
      labels:
        app: home-task-service
    spec:
      containers:
      - name: home-task-service
        image: pereira6/home-task-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-hometask"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "home_task_db"
        - name: DB_USER
          value: "grupo6_admin"
        - name: DB_PASSWORD
          value: "grupo6"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: home-task-service
spec:
  type: NodePort
  selector:
    app: home-task-service
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000 