apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home-task-service
  template:
    metadata:
      labels:
        app: home-task-service
    spec:
      containers:
      - name: home-task-service
        image: ${DOCKER_USERNAME}/home-task-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-hometask"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "home_task_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: home-task-service
spec:
  type: NodePort
  selector:
    app: home-task-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000 