apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-service
  template:
    metadata:
      labels:
        app: shopping-service
    spec:
      containers:
      - name: shopping-service
        image: pereira6/shopping-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: DB_HOST
          value: "postgres-shopping"
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: services-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: SHOPPING_DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: PORT
          value: "3003"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping-service
  ports:
  - port: 3003
    targetPort: 3003
    nodePort: 30003 