apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-service
  template:
    metadata:
      labels:
        app: shopping-service
    spec:
      containers:
      - name: shopping-service
        image: pereira6/shopping-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "postgres-shopping"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "shopping_service_db"
        - name: DB_USER
          value: "grupo6_admin"
        - name: DB_PASSWORD
          value: "grupo6"
        - name: PORT
          value: "3001"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping-service
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001 