apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-service
  template:
    metadata:
      labels:
        app: shopping-service
    spec:
      containers:
      - name: shopping-service
        image: ${DOCKER_USERNAME}/shopping-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "postgres-shopping"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "shopping_service_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping-service
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001 