apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-shopping
spec:
  serviceName: postgres-shopping
  replicas: 1
  selector:
    matchLabels:
      app: postgres-shopping
  template:
    metadata:
      labels:
        app: postgres-shopping
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: shopping_service_db
        - name: POSTGRES_USER
          value: grupo6_admin
        - name: POSTGRES_PASSWORD
          value: grupo6
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-shopping
spec:
  selector:
    app: postgres-shopping
  ports:
    - port: 5432
      targetPort: 5432 