version: '3.8'
 
services:
  # API Service
  api:
    container_name: api-user
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db-rel-user
      - DB_PORT=5432
      - DB_USER=grupo6_admin
      - DB_PASSWORD=grupo6
      - DB_NAME=user_service_db
      - PORT=3002
      - JWT_SECRET=your-secret-key
    ports:
      - "3002:3002"
    depends_on:
      - db-rel
    networks:
      - user-network

  # Watchtower para atualização automática
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 api
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
    networks:
      - app-network

  # PostgreSQL Database
  db-rel:
    container_name: db-rel-user
    build: docker/db
    volumes:
      - rel-data:/var/lib/postgresql/data
    ports:
      - "${EXP_PORT_PG_REL:-5434}:5432"
    networks:
      - user-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - app-network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  rel-data:
  prometheus-data:
  grafana-data:

networks:
  user-network:
    driver: bridge
  app-network:
    driver: bridge