name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: user-service
  DOCKER_TAG: latest

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./User_Service
  #   steps:
  #     - uses: actions/checkout@v2
      
  #     - name: Debug - Print Working Directory
  #       run: |
  #         pwd
  #         ls -la
  #         echo "Current directory structure:"
  #         tree -a
      
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '18'
          
  #     - name: Install dependencies
  #       run: npm ci
          
  #     - name: Run tests
  #       run: npm test

  build-and-push:
    # needs: test    # Comentado pois o job de teste está comentado
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service_dir: User_Service
            image_name: user-service
          - service_dir: Shopping_Service
            image_name: shopping-service
          - service_dir: Home_Task_Service
            image_name: home-task-service
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: pereira6
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service_dir }}
          push: true
          tags: pereira6/${{ matrix.image_name }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
      
      - name: Set up Minikube
        uses: medyagh/setup-minikube@master
      
      - name: Deploy to Minikube
        run: |
          minikube start --driver=docker
          
          # Enable ingress
          minikube addons enable ingress
          
          # Deploy databases first
          echo "Deploying databases..."
          kubectl apply -f kubernetes/user-service/postgres.yaml
          kubectl apply -f kubernetes/shopping-service/postgres.yaml
          kubectl apply -f kubernetes/home-task-service/postgres.yaml
          
          # Wait for databases to be ready
          echo "Waiting for databases to be ready..."
          kubectl wait --for=condition=ready pod -l app=postgres-user --timeout=180s
          kubectl wait --for=condition=ready pod -l app=postgres-shopping --timeout=180s
          kubectl wait --for=condition=ready pod -l app=postgres-hometask --timeout=180s
          
          # Deploy services
          echo "Deploying services..."
          kubectl apply -f kubernetes/user-service/deployment.yaml
          kubectl apply -f kubernetes/shopping-service/deployment.yaml
          kubectl apply -f kubernetes/home-task-service/deployment.yaml
          
          # Show status
          echo "Initial pod status:"
          kubectl get pods -o wide
          
          # Start tunnel in background
          echo "Starting minikube tunnel..."
          minikube tunnel &
          
          # Wait for services to be ready
          echo "Waiting for services to be ready..."
          kubectl wait --for=condition=ready pod -l app=user-service --timeout=180s
          kubectl wait --for=condition=ready pod -l app=shopping-service --timeout=180s
          kubectl wait --for=condition=ready pod -l app=home-task-service --timeout=180s
          
          # Show final status
          echo "Final pod status:"
          kubectl get pods -o wide
          
          echo "Service status:"
          kubectl get services -o wide
          
          echo "Node status:"
          kubectl get nodes -o wide
          
          # Get service URLs
          echo "Service URLs:"
          minikube service list
          
          # Test endpoints
          echo "Testing endpoints..."
          MINIKUBE_IP=$(minikube ip)
          
          echo "Testing User Service..."
          curl -v "http://${MINIKUBE_IP}:30002/health"
          
          echo "Testing Shopping Service..."
          curl -v "http://${MINIKUBE_IP}:30001/health"
          
          echo "Testing Home Task Service..."
          curl -v "http://${MINIKUBE_IP}:30000/health"