name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: pereira6
  MINIKUBE_VERSION: v1.32.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push User Service
      uses: docker/build-push-action@v5
      with:
        context: ./User_Service
        push: true
        tags: ${{ env.REGISTRY }}/user-service:latest

    - name: Build and push Shopping Service
      uses: docker/build-push-action@v5
      with:
        context: ./Shopping_Service
        push: true
        tags: ${{ env.REGISTRY }}/shopping-service:latest

    - name: Build and push Home Task Service
      uses: docker/build-push-action@v5
      with:
        context: ./Home_Task_Service
        push: true
        tags: ${{ env.REGISTRY }}/home-task-service:latest

    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
      with:
        minikube-version: ${{ env.MINIKUBE_VERSION }}

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/configmaps/
        kubectl apply -f kubernetes/secrets/
        kubectl apply -f kubernetes/user-service/
        kubectl apply -f kubernetes/shopping-service/
        kubectl apply -f kubernetes/home-task-service/

    - name: Wait for services
      run: |
        sleep 30s
        for pod in $(kubectl get pods -o name); do
          echo "=== Logs for $pod ==="
          kubectl logs $pod
          echo "=== End logs for $pod ==="
        done